### ISSUE TITLE
Using Ray with Docker can't open files

### ISSUE THREAD

**Issue by jasonmccallister** [spatie/laravel-ray#13]
I realize this is new but great work! I am running a Docker container and have Ray setup and working. However, my path in the container is `/app/public` and the Ray app defaults to the path from the container, not the host machine which makes sense.

Perhaps a config option to set the "file path/root" to the project would resolve this issue?

![Screen Shot 2021-01-07 at 12 14 23 PM](https://user-images.githubusercontent.com/5354908/103922540-e254bd00-50e1-11eb-9d56-d5d3071ec153.png)

![Screen Shot 2021-01-07 at 12 15 59 PM](https://user-images.githubusercontent.com/5354908/103922722-26e05880-50e2-11eb-8c9e-c07424c601cb.png)

**Comment by axelitus** [comment]
Like what PhpStorm does with the mapping directories, that would be great.

**Comment by SRWieZ** [comment]
A config like ignition would be great
https://github.com/facade/ignition/blob/master/config/ignition.php

But I wonder if this issue should not be in [spatie/ray](https://github.com/spatie/ray)

**Comment by freekmurze** [comment]
I'm not sure what you exactly need, but I'm open to a PR that solves your issue. Both `ray` and `laravel-ray` can use a configuration file: https://spatie.be/docs/ray/v1/getting-started/configuring-ray

**Comment by SRWieZ** [comment]
When we click on the link that should open the file where ray() has been called phpstorm trigger an error:
**Can not open file /home/vagrant/code/routes/web.php**

Because this file path corresponds the path inside docker/vagrant/etc..

Ignition resolve this by 2 env variable, for example my .env file:
```
IGNITION_REMOTE_SITES_PATH=/home/vagrant/code
IGNITION_LOCAL_SITES_PATH=/Users/eserdeniz/Projects/autobimi
```

I will love to PR but I'm not sure how to test the package on a laravel project. 😅

I suggest changing all the return statement of `getFrame()` to `$originFrame = ` 

then just before the return 
`$originFrame->file = Ray::replaceRemotePathWithLocalPath($originFrame->file);`

Then `replaceRemotePathWithLocalPath($file_path)` should be a function that take 2 parameters from the config and return `return str_replace($this->settings->remote_path, $this->settings->local_path, $file_path);`

Hope it's clear. Should work. Don't know if there is a better way to do it 🙂

**Comment by freekmurze** [comment]
> I will love to PR but I'm not sure how to test the package on a laravel project. 😅

Send a PR with changes that work for you, I'll take care of the tests

**Comment by freekmurze** [comment]
We'll continue this conversation in #23
