### ISSUE TITLE
Unable to receive calls in Homestead

### ISSUE THREAD

**Issue by rayblair06** [spatie/laravel-ray#15]
First of all, love the name!

I'm unable to receive any messages using Ray from Homestead, I wish I had more details but unfortunately the welcome never disappears and no errors appear.

Returns string but nothing ever appears in the Ray client.
```
Route::get('test', function () {
    ray('Hello');

    return 'done!';
});
```
![Screenshot 2021-01-07 at 17 26 14](https://user-images.githubusercontent.com/16214725/103924151-91f35480-510d-11eb-9056-f91343fa8c99.png)

macOS Cataline Version 10.15.7
Laravel 7.30.1 
Vagrant 2.2.14
Homestead 10.17.0
PHP 7.4.13

**Comment by bullenb** [comment]
I have got this working on my Homestead installation (albeit with a modification to the package code). Make sure your host in your config file is set to 10.0.2.2.

Due to an issue in the service provider, the host is not correctly applied to the request. I've submitted a pull request (#14) that fixes this.

**Comment by rayblair06** [comment]
Thank you @bullenb!

I was trying to configure it to no avail, your PR seems to have fixed my issues.

Closing due to future PR fixing issue.
