### ISSUE TITLE
Windows: Ray seems not be running at http://localhost:23517 

### ISSUE THREAD

**Issue by JunaidQadirB** [spatie/laravel-ray#24]
I've followed the instructions. but when I run my app with a `ray` call it gives this error:`Ray seems not be running at http://localhost:23517`

I'm using Winds 10 and using wsl2 to run my app using `php artisan serve`.

**Comment by gm-lunatix** [comment]
you need to use the windows host IP instead of localhost (which is pointing to your ws;l distro 127.0.0.1) If you're using docker you might already have something like host.docker.internal in your wsl2 /etc/hosts file. This host.docker.internal what I use in the vendor/spatie/ray/src/Settings/Settings.php file $defaultSettings:

`
    protected array $defaultSettings = [
        'host' => 'host.docker.internal',
        'port' => 23517,
    ];
`

until I figure out how to properly set the host. There might be a better or proper solution to this tho.

**Comment by atiqsamtia** [comment]
Happening same if ray app is closed. it should work just fine if ray app is not running as it's an optional dev tool.

**Comment by freekmurze** [comment]
This has been fixed in spatie/ray 1.1.1

Should this still give problems, please open an issue at https://github.com/spatie/ray

Make sure to post a full stack trace.

Thanks!

**Comment by JunaidQadirB** [comment]
Now it doesn't give any errors but also doesn't do anything as well.
