### ISSUE TITLE
issue #35 is not yet solved 

### ISSUE THREAD

**Issue by michabbb** [spatie/laravel-ray#43]
please reopen a not solved issue or at least help to understand what your customer is doing wrong

**Comment by freekmurze** [comment]
You can use the new *_path options to map remote to local paths:

https://spatie.be/docs/ray/v1/getting-started/configuring-ray

If this is not working, please open up a new issue mentioning in detail the paths you are using in the config, and the paths that you are seeing.

I don't have access to an environment you are working on, so you might do a little debugging yourself in the spatie/ray package.

Feel free to optionally submit a PR that solves this problem for your particular environment.

If you are unable to find a solution I'll glady refund your purchase.

**Comment by michabbb** [comment]
are you kidding me? I provided everything, screenshots included, I already debugged YOUR code. 

you would see that if you wouldn't close every issue after after 5 min with a useless comment. 

so just because YOU are not able to reproduce, the problem, it does not exist. wow, sounds like on of these corona deniers.

okay, I really tried my best here but I have better things to do to help someone who is great in making big announcements, videos and streams and getting money for a unfinished software, but when it comes to the point where people really wanna help, and then getting ignored all the time.

keep going on, closing issues does not solve problems, you will see, or probably not, with that kind of attitude 😠

**Comment by michabbb** [comment]
@freekmurze one last comment: 

you are offering ".exe" but at the same time telling people: "I don´t use windows, so fuck off" is a clear signal to everyone: 

**DO NOT INVEST ANY MONEY OR TIME INTO SUCH AN IGNORANT BUSINESS**

instead of being grateful that people want to help, you are treated as a disruptive factor, that's really the last thing!

**Comment by patinthehat** [comment]
@michabbb :-1: :-1: 
You don't know what you're talking about.  Instead of acting like a child and opening issues just to complain - then repeatedly responding just to be a jerk - you could have tried explaining your problem in a different way, offered more information about the issue, or asked for help with debugging if you're unclear on how to proceed.
I'd have been happy to try and help you debug the issue you're having, and I'm sure there are others that would've, too.

**Comment by freekmurze** [comment]
@michabbb

Because you clearly are not happy with the product, I have tried to refund you, but it seems that you have no valid license and were using the demo.

I will not tolerate any impolite behaviour. Posting middlefinger emojis doesn't help anyone. 
I therefore have decided to block you from our issue trackers. I hope you will (someday) understand.

If you need support, or want to continue the conversation in a polite way, please contact me by mail directly (freek@spatie.be).
