### ISSUE TITLE
Allow `model` to accept a `collection` of models

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-ray#69]
Also add a `models` method. 

I'd accept a PR with tests for this. 

If none such a PR comes in, I'll implement this myself soon.

**Comment by squatto** [comment]
What would you think about also allowing multiple args to `model()`? For example: `ray()->model($user, $admin)`

**Comment by freekmurze** [comment]
Yup, that's also an awesome idea!

**Comment by squatto** [comment]
My only thought is that this would/should lead to other single-arg methods allowing multiple args. `toJson()`, `json()`, `mailable()`, etc. What do you think?

**Comment by freekmurze** [comment]
I probably would not change them unless many people ask for that. 

For models, I think it's a good idea, because it's likely that people will work with multiple models simultaneously. I don't think you're likely to debug multiple mailables in one go.

**Comment by squatto** [comment]
Good point. I can see `toJson()` and `json()` being used with multiple args though. `toJson()` especially. I can see using it in similar scenarios to `model()`. e.g. `ray()->toJson($user, $admin)`.

**Comment by freekmurze** [comment]
Yup, I agree, I'll make these changes soon.

**Comment by squatto** [comment]
@freekmurze I just submitted #83 to allow multiple `?Model` arguments to the `model()` method. While I was putting that together I came across a question I wanted to run by you...

With a single `Model` argument we're able to check the type with:

```php
public function model(?Model $model): self
```

With multiple `Model` arguments we're able to check the type with:

```php
public function model(?Model ...$models): self
```

However, in order to accept an `array` or `Collection` of type `Model` - and correct me if I'm wrong - it would have to be non-typed:

```php
public function model($models): self
```

This completely removes the benefit of a native type check and forces us to do it all ourselves. We'd have to:
1. Check if `$models` is `null` or `Model` and output a single `ModelPayload` if so
2. Check if `$models` is an `array` or `Collection` and map each member to `ModelPayload` and output it

However, the 2nd check brings up a question: what do we do if any of the `array`/`Collection` members _isn't_ `null` or `Model`? Throw an exception?

**Comment by freekmurze** [comment]
I've decided not to add support for `array` and `collections` until more people would ask for it.

**Comment by freekmurze** [comment]
Closing this one for now. Thanks for your help with this.

**Comment by squatto** [comment]
I think that's a good move for now. It's easy enough to just do `ray()->model(...$array)` 👍🏻

I'm happy to help! Would you like me to make the same type of change to `json()` and `toJson()` that I made to `model()`?

**Comment by freekmurze** [comment]
> Would you like me to make the same type of change to json() and toJson() that I made to model()?

Yup, make sure that you include tests and update docs just like last time. Thanks again.

**Comment by squatto** [comment]
@freekmurze the app seems to only be displaying the last payload being sent:

![image](https://user-images.githubusercontent.com/748444/104480102-7068f180-5581-11eb-95c7-723d6f971d2e.png)

This is when using the an updated `toJson()`:

```php
/**
 * Sends the provided value(s) encoded as a JSON string using json_encode().
 */
public function toJson(...$values): self
{
    $payloads = array_map(function ($value) {
        return new JsonStringPayload($value);
    }, $values);

    return $this->sendRequest($payloads);
}
```

I threw `dump($payloads)` in to verify that it has multiple payloads:

![image](https://user-images.githubusercontent.com/748444/104480423-ca69b700-5581-11eb-99ab-5bae003387b4.png)

Is this a bug or should multiple payloads be passed to `sendRequest()` in a different way?

**Comment by freekmurze** [comment]
I'm thinking it is a bug which we should fix within the app 
cc @AdrianMrn

**Comment by squatto** [comment]
OK, I'll submit a PR for the updated `json()` and `toJson()` methods/docs while you check into that

**Comment by squatto** [comment]
I just submitted [PR #148](https://github.com/spatie/ray/pull/148) on `spatie/ray` to update `json()` and `toJson()` 👍🏻

**Comment by mikeerickson** [comment]
> I've decided not to add support for `array` and `collections` until more people would ask for it.

Please add my vote for adding this feature
